version: '3.8'
name: divain
services:
  divain-frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: divain-frontend
    hostname: divain-frontend
    ports:
      - '3000:3000'
    restart: always

  divain-backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: divain-backend
    hostname: divain-backend
    ports:
      - '4224:4224'
    restart: always
